# Generated by Django 4.0.6 on 2022-07-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='star',
        ),
        migrations.RemoveField(
            model_name='roomstar',
            name='ip',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP адрес')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Комнаты')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomstar', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Ретинг',
                'verbose_name_plural': 'Ретинги',
            },
        ),
    ]
