# Generated by Django 4.0.6 on 2022-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('your_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.URLField(verbose_name='URL')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='OurAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(verbose_name='URL')),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'verbose_name': 'Наши данные',
                'verbose_name_plural': 'Наши данные',
            },
        ),
    ]
