# Generated by Django 4.0.6 on 2022-07-21 20:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Удобства',
                'verbose_name_plural': 'Удобства',
            },
        ),
    ]
