# Generated by Django 4.0.6 on 2022-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_image_about_сustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo_person', models.ImageField(upload_to='photo_person', verbose_name='Фото персонала')),
                ('info_person', models.TextField(max_length=500, verbose_name='Информация о персонале')),
                ('country_from', models.CharField(max_length=150, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Личный персонал',
                'verbose_name_plural': 'Личный персонал',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'О персонале', 'verbose_name_plural': 'О персонале'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='сustomer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country_from',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='info_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
